name: Post Product Updates

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  slack-post:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest

    steps:
      - name: Post Message
        env:
          SLACK_WEBHOOK_URL: ${{secrets.PRODUCT_UPDATES_SLACK_URL}}
          GITHUB_CONTEXT: ${{ toJson(github.event.pull_request) }}
        run: |
          echo $GITHUB_CONTEXT
          PR_BODY="${{github.event.pull_request.body}}"
          CLEANED_PR_BODY=$(echo "${PR_BODY:0:70}" | tr '\r' '\n')
          TITLE="${{github.event.pull_request.title}}"
          ADDITIONS="${{github.event.pull_request.additions}}"
          DELETIONS="${{github.event.pull_request.deletions}}"
          REPO_NAME="${{github.event.pull_request.head.repo.name}}"
          LINK="${{github.event.pull_request.html_url}}"
          USER="${{github.event.pull_request.user.login}}"
          TEXT="\n<${LINK}|${REPO_NAME}>: *${TITLE}*\n_Author: ${USER}_\n\`\`\`${CLEANED_PR_BODY}...\`\`\`\n"

          IMAGE_URLS=$(echo "${PR_BODY}" | sed -n 's/.*\(https:\/\/\github.com\/[a-z].*\/[a-z0-9-]*\).*/\1/p')
          echo "image urls : ${IMAGE_URLS}"
          for URL in $IMAGE_URLS; do
            TEXT="${TEXT}<${URL}|Image>    "
          done

          PAYLOAD="{\"blocks\":[{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"${TEXT}\n\"}}]}"
          echo $PAYLOAD

          curl '${{env.SLACK_WEBHOOK_URL}}' \
            -X 'POST' \
            -d "${PAYLOAD}"
